Basic authorization and authentication mechanism
HowDidUGetOutOfBounds/Rieltor-API pull request #4
Opened 2024-03-08 07:52 UTC by loxlouro

2024-03-09 16:00 UTC, HowDidUGetOutOfBounds requested changes

2024-03-09 16:00 UTC, HowDidUGetOutOfBounds commented on src/main/kotlin/com/reappa/rieltorapp/RieltorAppApplication.kt
> +//    @Autowired
do not leave ghost code

2024-03-09 16:00 UTC, HowDidUGetOutOfBounds commented on src/main/kotlin/com/reappa/rieltorapp/config/BeanContainer.kt
> +
to much whitespaces

2024-03-09 16:00 UTC, HowDidUGetOutOfBounds commented on src/main/kotlin/com/reappa/rieltorapp/dtos/RegistrationDto.kt
> +//@Data
remove ghost code

2024-03-09 16:00 UTC, HowDidUGetOutOfBounds commented on src/main/kotlin/com/reappa/rieltorapp/models/Role.kt
> +//    @get:JvmName("getRoleId")
remove ghost code

2024-03-09 16:00 UTC, HowDidUGetOutOfBounds commented on src/main/kotlin/com/reappa/rieltorapp/services/AccountService.kt
> +//        @Bean
remove ghost code

2024-03-10 16:00 UTC, loxlouro reviewed
Fixes after review

2024-03-10 16:01 UTC, merged